name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build-ps2:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash

    - name: Compile project
      run: |
        make -f Makefile.libretro platform=ps2 clean all
        git clone https://github.com/AKuHAK/RetroArch.git -b ps2_hdd --depth 1
        cp fceumm_libretro_ps2.a ./RetroArch/libretro_ps2.a
        cd ./RetroArch
        make -f Makefile.ps2.salamander -j1 debug
        make -f Makefile.ps2 -j1 debug

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: fceumm_libretro_ps2-${{ steps.slug.outputs.sha8 }}
        path: |
          *.elf
          *.ELF
          RetroArch/*.elf
